/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) grad_f_X_fcn_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s6[8] = {3, 3, 0, 0, 1, 2, 2, 1};
static const casadi_int casadi_s7[15] = {0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s8[15] = {0, 2, 4, 18, 21, 24, 27, 33, 39, 45, 51, 57, 63, 69, 75};
static const casadi_int casadi_s9[3] = {0, 0, 0};
static const casadi_int casadi_s10[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s11[8] = {3, 3, 0, 1, 1, 2, 2, 0};
static const casadi_int casadi_s12[18] = {1, 3, 5, 6, 10, 14, 19, 22, 25, 28, 34, 40, 46, 52, 58, 64, 70, 76};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s14[8] = {3, 3, 0, 1, 2, 2, 1, 0};
static const casadi_int casadi_s15[12] = {20, 23, 26, 29, 35, 41, 47, 53, 59, 65, 71, 77};
static const casadi_int casadi_s16[9] = {3, 3, 0, 3, 3, 3, 0, 1, 2};
static const casadi_int casadi_s17[12] = {3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s18[12] = {7, 11, 15, 30, 36, 42, 48, 54, 60, 66, 72, 78};
static const casadi_int casadi_s19[9] = {3, 3, 0, 0, 3, 3, 0, 1, 2};
static const casadi_int casadi_s20[12] = {8, 12, 16, 31, 37, 43, 49, 55, 61, 67, 73, 79};
static const casadi_int casadi_s21[9] = {3, 3, 0, 0, 0, 3, 0, 1, 2};
static const casadi_int casadi_s22[12] = {9, 13, 17, 32, 38, 44, 50, 56, 62, 68, 74, 80};
static const casadi_int casadi_s23[102] = {18, 18, 0, 1, 2, 3, 5, 7, 9, 21, 33, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 0, 1, 2, 0, 3, 1, 4, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 3, 9, 12, 15, 4, 10, 13, 16, 5, 11, 14, 17, 3, 9, 12, 15, 4, 10, 13, 16, 5, 11, 14, 17, 3, 9, 12, 15, 4, 10, 13, 16, 5, 11, 14, 17};
static const casadi_int casadi_s24[102] = {18, 18, 0, 2, 4, 6, 10, 14, 18, 21, 24, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 0, 3, 1, 4, 2, 5, 3, 9, 12, 15, 4, 10, 13, 16, 5, 11, 14, 17, 6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8, 9, 12, 15, 6, 7, 8, 10, 13, 16, 6, 7, 8, 11, 14, 17, 6, 7, 8, 9, 12, 15, 6, 7, 8, 10, 13, 16, 6, 7, 8, 11, 14, 17, 6, 7, 8, 9, 12, 15, 6, 7, 8, 10, 13, 16, 6, 7, 8, 11, 14, 17};
static const casadi_int casadi_s25[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s26[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s27[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[3] = {1., 0., 0.};
static const casadi_real casadi_c1[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c2[3] = {0., 1., 0.};
static const casadi_real casadi_c3[3] = {0., 0., 1.};

/* grad_f_X_fcn:(i0[18],i1[4],i2,i3,i4[3x3])->(o0[18x18,81nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+84, *w2=w+102, *w3=w+105, w4, *w5=w+109, *w6=w+118, *w7=w+127, *w8=w+130, w9, *w10=w+140, w11, w12, *w13=w+160, *w14=w+163, *w15=w+166, *w16=w+169, *w17=w+178, *w21=w+187, *w22=w+189, *w23=w+191, *w24=w+200, w25, w26, w27, w28, *w29=w+213, w30, w31, w32, *w33=w+225, *w34=w+234, *w35=w+243, w36, *w37=w+253, *w38=w+262, w39, *w40=w+272, *w41=w+281, w42, *w43=w+297, *w44=w+309, *w45=w+313;
  /* #0: @0 = zeros(18x18,81nz) */
  casadi_clear(w0, 81);
  /* #1: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #2: @2 = ones(1x3) */
  casadi_fill(w2, 3, 1.);
  /* #3: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #4: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #5: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #6: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #7: (@1[6:9] = @2) */
  for (rr=w1+6, ss=w2; rr!=w1+9; rr+=1) *rr = *ss++;
  /* #8: @2 = [1, 0, 0] */
  casadi_copy(casadi_c0, 3, w2);
  /* #9: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #10: @4 = input[2][0] */
  w4 = arg[2] ? arg[2][0] : 0;
  /* #11: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w5);
  /* #12: @6 = input[4][0] */
  casadi_copy(arg[4], 9, w6);
  /* #13: @5 = (@6\@5) */
  rr = w5;
  ss = w6;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #14: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) (*rr++)  = (w4*(*cs++));
  /* #15: @7 = zeros(3x1) */
  casadi_clear(w7, 3);
  /* #16: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @10 = input[0][0] */
  casadi_copy(arg[0], 18, w10);
  /* #19: @11 = @10[8] */
  for (rr=(&w11), ss=w10+8; ss!=w10+9; ss+=1) *rr++ = *ss;
  /* #20: @11 = (-@11) */
  w11 = (- w11 );
  /* #21: @12 = @10[7] */
  for (rr=(&w12), ss=w10+7; ss!=w10+8; ss+=1) *rr++ = *ss;
  /* #22: @13 = horzcat(@9, @11, @12) */
  rr=w13;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  /* #23: @13 = @13' */
  /* #24: @9 = @10[8] */
  for (rr=(&w9), ss=w10+8; ss!=w10+9; ss+=1) *rr++ = *ss;
  /* #25: @11 = 0 */
  w11 = 0.;
  /* #26: @12 = @10[6] */
  for (rr=(&w12), ss=w10+6; ss!=w10+7; ss+=1) *rr++ = *ss;
  /* #27: @12 = (-@12) */
  w12 = (- w12 );
  /* #28: @14 = horzcat(@9, @11, @12) */
  rr=w14;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  /* #29: @14 = @14' */
  /* #30: @9 = @10[7] */
  for (rr=(&w9), ss=w10+7; ss!=w10+8; ss+=1) *rr++ = *ss;
  /* #31: @9 = (-@9) */
  w9 = (- w9 );
  /* #32: @11 = @10[6] */
  for (rr=(&w11), ss=w10+6; ss!=w10+7; ss+=1) *rr++ = *ss;
  /* #33: @12 = 0 */
  w12 = 0.;
  /* #34: @15 = horzcat(@9, @11, @12) */
  rr=w15;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  /* #35: @15 = @15' */
  /* #36: @16 = horzcat(@13, @14, @15) */
  rr=w16;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #37: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #38: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<9; ++i) *rr++ = (- *cs++ );
  /* #39: @8 = mac(@17,@6,@8) */
  for (i=0, rr=w8; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #40: @9 = ones(3x1,1nz) */
  w9 = 1.;
  /* #41: @7 = mac(@8,@9,@7) */
  casadi_mtimes(w8, casadi_s1, (&w9), casadi_s5, w7, casadi_s4, w, 0);
  /* #42: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #43: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #44: @18 = zeros(3x1,0nz) */
  /* #45: @19 = 00 */
  /* #46: @20 = 00 */
  /* #47: @9 = -1 */
  w9 = -1.;
  /* #48: @11 = horzcat(@19, @20, @9) */
  rr=(&w11);
  *rr++ = w9;
  /* #49: @11 = @11' */
  /* #50: @19 = 00 */
  /* #51: @9 = 1 */
  w9 = 1.;
  /* #52: @20 = 00 */
  /* #53: @12 = horzcat(@19, @9, @20) */
  rr=(&w12);
  *rr++ = w9;
  /* #54: @12 = @12' */
  /* #55: @21 = horzcat(@18, @11, @12) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w12;
  /* #56: @22 = @21' */
  casadi_trans(w21,casadi_s6, w22, casadi_s6, iw);
  /* #57: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<2; ++i) *rr++ = (- *cs++ );
  /* #58: @17 = mac(@22,@6,@17) */
  casadi_mtimes(w22, casadi_s6, w6, casadi_s1, w17, casadi_s1, w, 0);
  /* #59: @14 = @10[6:9] */
  for (rr=w14, ss=w10+6; ss!=w10+9; ss+=1) *rr++ = *ss;
  /* #60: @13 = mac(@17,@14,@13) */
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: @7 = (@7+@13) */
  for (i=0, rr=w7, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #62: @3 = mac(@5,@7,@3) */
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #63: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #64: @2 = @2' */
  /* #65: (@1[6:9] += @2) */
  for (rr=w1+6, ss=w2; rr!=w1+9; rr+=1) *rr += *ss++;
  /* #66: @17 = zeros(1x9) */
  casadi_clear(w17, 9);
  /* #67: (@1[9:18] = @17) */
  for (rr=w1+9, ss=w17; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #68: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #69: @16 = @10[9:18] */
  for (rr=w16, ss=w10+9; ss!=w10+18; ss+=1) *rr++ = *ss;
  /* #70: @16 = reshape(@16) */
  /* #71: @11 = 0 */
  w11 = 0.;
  /* #72: @2 = (@14*@4) */
  for (i=0, rr=w2, cr=w14; i<3; ++i) (*rr++)  = ((*cr++)*w4);
  /* #73: @12 = @2[2] */
  for (rr=(&w12), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #74: @12 = (-@12) */
  w12 = (- w12 );
  /* #75: @9 = @2[1] */
  for (rr=(&w9), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #76: @3 = horzcat(@11, @12, @9) */
  rr=w3;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  /* #77: @3 = @3' */
  /* #78: @11 = @2[2] */
  for (rr=(&w11), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #79: @12 = 0 */
  w12 = 0.;
  /* #80: @9 = @2[0] */
  for (rr=(&w9), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #81: @9 = (-@9) */
  w9 = (- w9 );
  /* #82: @7 = horzcat(@11, @12, @9) */
  rr=w7;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  /* #83: @7 = @7' */
  /* #84: @11 = @2[1] */
  for (rr=(&w11), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #85: @11 = (-@11) */
  w11 = (- w11 );
  /* #86: @12 = @2[0] */
  for (rr=(&w12), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #87: @9 = 0 */
  w9 = 0.;
  /* #88: @2 = horzcat(@11, @12, @9) */
  rr=w2;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w9;
  /* #89: @2 = @2' */
  /* #90: @23 = horzcat(@3, @7, @2) */
  rr=w23;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #91: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #92: @3 = (@14*@4) */
  for (i=0, rr=w3, cr=w14; i<3; ++i) (*rr++)  = ((*cr++)*w4);
  /* #93: @11 = ||@3||_F */
  w11 = sqrt(casadi_dot(3, w3, w3));
  /* #94: @12 = cos(@11) */
  w12 = cos( w11 );
  /* #95: @9 = project(@3) */
  casadi_sparsify(w3, (&w9), casadi_s5, 0);
  /* #96: @25 = sparsity_cast(@4) */
  casadi_copy((&w4), 1, (&w25));
  /* #97: @26 = dot(@9, @25) */
  w26 = casadi_dot(1, (&w9), (&w25));
  /* #98: @26 = (@26/@11) */
  w26 /= w11;
  /* #99: @9 = (@12*@26) */
  w9  = (w12*w26);
  /* #100: @9 = (@9/@11) */
  w9 /= w11;
  /* #101: @25 = sin(@11) */
  w25 = sin( w11 );
  /* #102: @25 = (@25/@11) */
  w25 /= w11;
  /* #103: @27 = (@25/@11) */
  w27  = (w25/w11);
  /* #104: @28 = (@27*@26) */
  w28  = (w27*w26);
  /* #105: @9 = (@9-@28) */
  w9 -= w28;
  /* #106: @23 = (@24*@9) */
  for (i=0, rr=w23, cr=w24; i<9; ++i) (*rr++)  = ((*cr++)*w9);
  /* #107: @18 = zeros(3x1,0nz) */
  /* #108: @19 = 00 */
  /* #109: @20 = 00 */
  /* #110: @9 = (-@4) */
  w9 = (- w4 );
  /* #111: @28 = horzcat(@19, @20, @9) */
  rr=(&w28);
  *rr++ = w9;
  /* #112: @28 = @28' */
  /* #113: @19 = 00 */
  /* #114: @20 = 00 */
  /* #115: @9 = horzcat(@19, @4, @20) */
  rr=(&w9);
  *rr++ = w4;
  /* #116: @9 = @9' */
  /* #117: @22 = horzcat(@18, @28, @9) */
  rr=w22;
  *rr++ = w28;
  *rr++ = w9;
  /* #118: @21 = @22' */
  casadi_trans(w22,casadi_s6, w21, casadi_s6, iw);
  /* #119: @21 = (@25*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w25*(*cs++));
  /* #120: @29 = dense(@21) */
  casadi_densify(w21, casadi_s6, w29, 0);
  /* #121: @23 = (@23+@29) */
  for (i=0, rr=w23, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #122: @29 = zeros(3x3) */
  casadi_clear(w29, 9);
  /* #123: @28 = 1 */
  w28 = 1.;
  /* #124: @9 = cos(@11) */
  w9 = cos( w11 );
  /* #125: @28 = (@28-@9) */
  w28 -= w9;
  /* #126: @9 = sq(@11) */
  w9 = casadi_sq( w11 );
  /* #127: @28 = (@28/@9) */
  w28 /= w9;
  /* #128: @30 = 0 */
  w30 = 0.;
  /* #129: @7 = (@14*@4) */
  for (i=0, rr=w7, cr=w14; i<3; ++i) (*rr++)  = ((*cr++)*w4);
  /* #130: @31 = @7[2] */
  for (rr=(&w31), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #131: @31 = (-@31) */
  w31 = (- w31 );
  /* #132: @32 = @7[1] */
  for (rr=(&w32), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #133: @2 = horzcat(@30, @31, @32) */
  rr=w2;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #134: @2 = @2' */
  /* #135: @30 = @7[2] */
  for (rr=(&w30), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #136: @31 = 0 */
  w31 = 0.;
  /* #137: @32 = @7[0] */
  for (rr=(&w32), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #138: @32 = (-@32) */
  w32 = (- w32 );
  /* #139: @13 = horzcat(@30, @31, @32) */
  rr=w13;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #140: @13 = @13' */
  /* #141: @30 = @7[1] */
  for (rr=(&w30), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #142: @30 = (-@30) */
  w30 = (- w30 );
  /* #143: @31 = @7[0] */
  for (rr=(&w31), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #144: @32 = 0 */
  w32 = 0.;
  /* #145: @7 = horzcat(@30, @31, @32) */
  rr=w7;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #146: @7 = @7' */
  /* #147: @33 = horzcat(@2, @13, @7) */
  rr=w33;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  /* #148: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #149: @33 = (@28*@34) */
  for (i=0, rr=w33, cs=w34; i<9; ++i) (*rr++)  = (w28*(*cs++));
  /* #150: @18 = zeros(3x1,0nz) */
  /* #151: @19 = 00 */
  /* #152: @20 = 00 */
  /* #153: @30 = (-@4) */
  w30 = (- w4 );
  /* #154: @31 = horzcat(@19, @20, @30) */
  rr=(&w31);
  *rr++ = w30;
  /* #155: @31 = @31' */
  /* #156: @19 = 00 */
  /* #157: @20 = 00 */
  /* #158: @30 = horzcat(@19, @4, @20) */
  rr=(&w30);
  *rr++ = w4;
  /* #159: @30 = @30' */
  /* #160: @21 = horzcat(@18, @31, @30) */
  rr=w21;
  *rr++ = w31;
  *rr++ = w30;
  /* #161: @22 = @21' */
  casadi_trans(w21,casadi_s6, w22, casadi_s6, iw);
  /* #162: @29 = mac(@33,@22,@29) */
  casadi_mtimes(w33, casadi_s1, w22, casadi_s6, w29, casadi_s1, w, 0);
  /* #163: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #164: @31 = sin(@11) */
  w31 = sin( w11 );
  /* #165: @30 = (@31*@26) */
  w30  = (w31*w26);
  /* #166: @30 = (@30/@9) */
  w30 /= w9;
  /* #167: @32 = (@28/@9) */
  w32  = (w28/w9);
  /* #168: @36 = (2.*@11) */
  w36 = (2.* w11 );
  /* #169: @26 = (@36*@26) */
  w26  = (w36*w26);
  /* #170: @26 = (@32*@26) */
  w26  = (w32*w26);
  /* #171: @30 = (@30-@26) */
  w30 -= w26;
  /* #172: @37 = (@34*@30) */
  for (i=0, rr=w37, cr=w34; i<9; ++i) (*rr++)  = ((*cr++)*w30);
  /* #173: @18 = zeros(3x1,0nz) */
  /* #174: @19 = 00 */
  /* #175: @20 = 00 */
  /* #176: @30 = (-@4) */
  w30 = (- w4 );
  /* #177: @26 = horzcat(@19, @20, @30) */
  rr=(&w26);
  *rr++ = w30;
  /* #178: @26 = @26' */
  /* #179: @19 = 00 */
  /* #180: @20 = 00 */
  /* #181: @30 = horzcat(@19, @4, @20) */
  rr=(&w30);
  *rr++ = w4;
  /* #182: @30 = @30' */
  /* #183: @22 = horzcat(@18, @26, @30) */
  rr=w22;
  *rr++ = w26;
  *rr++ = w30;
  /* #184: @21 = @22' */
  casadi_trans(w22,casadi_s6, w21, casadi_s6, iw);
  /* #185: @21 = (@28*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w28*(*cs++));
  /* #186: @38 = dense(@21) */
  casadi_densify(w21, casadi_s6, w38, 0);
  /* #187: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #188: @26 = 0 */
  w26 = 0.;
  /* #189: @2 = (@14*@4) */
  for (i=0, rr=w2, cr=w14; i<3; ++i) (*rr++)  = ((*cr++)*w4);
  /* #190: @30 = @2[2] */
  for (rr=(&w30), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #191: @30 = (-@30) */
  w30 = (- w30 );
  /* #192: @39 = @2[1] */
  for (rr=(&w39), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #193: @13 = horzcat(@26, @30, @39) */
  rr=w13;
  *rr++ = w26;
  *rr++ = w30;
  *rr++ = w39;
  /* #194: @13 = @13' */
  /* #195: @26 = @2[2] */
  for (rr=(&w26), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #196: @30 = 0 */
  w30 = 0.;
  /* #197: @39 = @2[0] */
  for (rr=(&w39), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #198: @39 = (-@39) */
  w39 = (- w39 );
  /* #199: @7 = horzcat(@26, @30, @39) */
  rr=w7;
  *rr++ = w26;
  *rr++ = w30;
  *rr++ = w39;
  /* #200: @7 = @7' */
  /* #201: @26 = @2[1] */
  for (rr=(&w26), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #202: @26 = (-@26) */
  w26 = (- w26 );
  /* #203: @30 = @2[0] */
  for (rr=(&w30), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #204: @39 = 0 */
  w39 = 0.;
  /* #205: @2 = horzcat(@26, @30, @39) */
  rr=w2;
  *rr++ = w26;
  *rr++ = w30;
  *rr++ = w39;
  /* #206: @2 = @2' */
  /* #207: @38 = horzcat(@13, @7, @2) */
  rr=w38;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #208: @40 = @38' */
  for (i=0, rr=w40, cs=w38; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #209: @35 = mac(@37,@40,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w37+j, tt=w40+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #210: @29 = (@29+@35) */
  for (i=0, rr=w29, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #211: @23 = (@23+@29) */
  for (i=0, rr=w23, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #212: @17 = mac(@16,@23,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #213: @17 = reshape(@17) */
  /* #214: (@1[9:18] += @17) */
  for (rr=w1+9, ss=w17; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #215: @41 = @1[0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] */
  for (cii=casadi_s7, rr=w41, ss=w1; cii!=casadi_s7+15; ++cii) *rr++ = ss[*cii];
  /* #216: (@0[0, 2, 4, 18, 21, 24, 27, 33, 39, 45, 51, 57, 63, 69, 75] = @41) */
  for (cii=casadi_s8, rr=w0, ss=w41; cii!=casadi_s8+15; ++cii, ++ss) rr[*cii] = *ss;
  /* #217: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #218: @13 = @4[0, 0, 0] */
  for (cii=casadi_s9, rr=w13, ss=(&w4); cii!=casadi_s9+3; ++cii) *rr++ = ss[*cii];
  /* #219: @13 = @13' */
  /* #220: (@1[:3] += @13) */
  for (rr=w1+0, ss=w13; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #221: @13 = zeros(1x3) */
  casadi_clear(w13, 3);
  /* #222: (@1[3:6] = @13) */
  for (rr=w1+3, ss=w13; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #223: @13 = ones(1x3) */
  casadi_fill(w13, 3, 1.);
  /* #224: (@1[3:6] += @13) */
  for (rr=w1+3, ss=w13; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #225: @13 = zeros(1x3) */
  casadi_clear(w13, 3);
  /* #226: (@1[6:9] = @13) */
  for (rr=w1+6, ss=w13; rr!=w1+9; rr+=1) *rr = *ss++;
  /* #227: @13 = [0, 1, 0] */
  casadi_copy(casadi_c2, 3, w13);
  /* #228: @7 = zeros(3x1) */
  casadi_clear(w7, 3);
  /* #229: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #230: @26 = ones(3x1,1nz) */
  w26 = 1.;
  /* #231: @2 = mac(@8,@26,@2) */
  casadi_mtimes(w8, casadi_s1, (&w26), casadi_s10, w2, casadi_s4, w, 0);
  /* #232: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #233: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #234: @18 = 00 */
  /* #235: @19 = 00 */
  /* #236: @26 = 1 */
  w26 = 1.;
  /* #237: @30 = horzcat(@18, @19, @26) */
  rr=(&w30);
  *rr++ = w26;
  /* #238: @30 = @30' */
  /* #239: @18 = zeros(3x1,0nz) */
  /* #240: @26 = -1 */
  w26 = -1.;
  /* #241: @19 = 00 */
  /* #242: @20 = 00 */
  /* #243: @39 = horzcat(@26, @19, @20) */
  rr=(&w39);
  *rr++ = w26;
  /* #244: @39 = @39' */
  /* #245: @21 = horzcat(@30, @18, @39) */
  rr=w21;
  *rr++ = w30;
  *rr++ = w39;
  /* #246: @22 = @21' */
  casadi_trans(w21,casadi_s11, w22, casadi_s11, iw);
  /* #247: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<2; ++i) *rr++ = (- *cs++ );
  /* #248: @17 = mac(@22,@6,@17) */
  casadi_mtimes(w22, casadi_s11, w6, casadi_s1, w17, casadi_s1, w, 0);
  /* #249: @15 = mac(@17,@14,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #250: @2 = (@2+@15) */
  for (i=0, rr=w2, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #251: @7 = mac(@5,@2,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #252: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #253: @13 = @13' */
  /* #254: (@1[6:9] += @13) */
  for (rr=w1+6, ss=w13; rr!=w1+9; rr+=1) *rr += *ss++;
  /* #255: @17 = zeros(1x9) */
  casadi_clear(w17, 9);
  /* #256: (@1[9:18] = @17) */
  for (rr=w1+9, ss=w17; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #257: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #258: @30 = project(@3) */
  casadi_sparsify(w3, (&w30), casadi_s10, 0);
  /* #259: @39 = sparsity_cast(@4) */
  casadi_copy((&w4), 1, (&w39));
  /* #260: @26 = dot(@30, @39) */
  w26 = casadi_dot(1, (&w30), (&w39));
  /* #261: @26 = (@26/@11) */
  w26 /= w11;
  /* #262: @30 = (@12*@26) */
  w30  = (w12*w26);
  /* #263: @30 = (@30/@11) */
  w30 /= w11;
  /* #264: @39 = (@27*@26) */
  w39  = (w27*w26);
  /* #265: @30 = (@30-@39) */
  w30 -= w39;
  /* #266: @23 = (@24*@30) */
  for (i=0, rr=w23, cr=w24; i<9; ++i) (*rr++)  = ((*cr++)*w30);
  /* #267: @18 = 00 */
  /* #268: @19 = 00 */
  /* #269: @30 = horzcat(@18, @19, @4) */
  rr=(&w30);
  *rr++ = w4;
  /* #270: @30 = @30' */
  /* #271: @18 = zeros(3x1,0nz) */
  /* #272: @39 = (-@4) */
  w39 = (- w4 );
  /* #273: @19 = 00 */
  /* #274: @20 = 00 */
  /* #275: @42 = horzcat(@39, @19, @20) */
  rr=(&w42);
  *rr++ = w39;
  /* #276: @42 = @42' */
  /* #277: @22 = horzcat(@30, @18, @42) */
  rr=w22;
  *rr++ = w30;
  *rr++ = w42;
  /* #278: @21 = @22' */
  casadi_trans(w22,casadi_s11, w21, casadi_s11, iw);
  /* #279: @21 = (@25*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w25*(*cs++));
  /* #280: @29 = dense(@21) */
  casadi_densify(w21, casadi_s11, w29, 0);
  /* #281: @23 = (@23+@29) */
  for (i=0, rr=w23, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #282: @29 = zeros(3x3) */
  casadi_clear(w29, 9);
  /* #283: @18 = 00 */
  /* #284: @19 = 00 */
  /* #285: @30 = horzcat(@18, @19, @4) */
  rr=(&w30);
  *rr++ = w4;
  /* #286: @30 = @30' */
  /* #287: @18 = zeros(3x1,0nz) */
  /* #288: @42 = (-@4) */
  w42 = (- w4 );
  /* #289: @19 = 00 */
  /* #290: @20 = 00 */
  /* #291: @39 = horzcat(@42, @19, @20) */
  rr=(&w39);
  *rr++ = w42;
  /* #292: @39 = @39' */
  /* #293: @21 = horzcat(@30, @18, @39) */
  rr=w21;
  *rr++ = w30;
  *rr++ = w39;
  /* #294: @22 = @21' */
  casadi_trans(w21,casadi_s11, w22, casadi_s11, iw);
  /* #295: @29 = mac(@33,@22,@29) */
  casadi_mtimes(w33, casadi_s1, w22, casadi_s11, w29, casadi_s1, w, 0);
  /* #296: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #297: @30 = (@31*@26) */
  w30  = (w31*w26);
  /* #298: @30 = (@30/@9) */
  w30 /= w9;
  /* #299: @26 = (@36*@26) */
  w26  = (w36*w26);
  /* #300: @26 = (@32*@26) */
  w26  = (w32*w26);
  /* #301: @30 = (@30-@26) */
  w30 -= w26;
  /* #302: @37 = (@34*@30) */
  for (i=0, rr=w37, cr=w34; i<9; ++i) (*rr++)  = ((*cr++)*w30);
  /* #303: @18 = 00 */
  /* #304: @19 = 00 */
  /* #305: @30 = horzcat(@18, @19, @4) */
  rr=(&w30);
  *rr++ = w4;
  /* #306: @30 = @30' */
  /* #307: @18 = zeros(3x1,0nz) */
  /* #308: @26 = (-@4) */
  w26 = (- w4 );
  /* #309: @19 = 00 */
  /* #310: @20 = 00 */
  /* #311: @39 = horzcat(@26, @19, @20) */
  rr=(&w39);
  *rr++ = w26;
  /* #312: @39 = @39' */
  /* #313: @22 = horzcat(@30, @18, @39) */
  rr=w22;
  *rr++ = w30;
  *rr++ = w39;
  /* #314: @21 = @22' */
  casadi_trans(w22,casadi_s11, w21, casadi_s11, iw);
  /* #315: @21 = (@28*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w28*(*cs++));
  /* #316: @38 = dense(@21) */
  casadi_densify(w21, casadi_s11, w38, 0);
  /* #317: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #318: @35 = mac(@37,@40,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w37+j, tt=w40+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #319: @29 = (@29+@35) */
  for (i=0, rr=w29, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #320: @23 = (@23+@29) */
  for (i=0, rr=w23, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #321: @17 = mac(@16,@23,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #322: @17 = reshape(@17) */
  /* #323: (@1[9:18] += @17) */
  for (rr=w1+9, ss=w17; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #324: (@0[1, 3, 5, 6, 10, 14, 19, 22, 25, 28, 34, 40, 46, 52, 58, 64, 70, 76] = @1) */
  for (cii=casadi_s12, rr=w0, ss=w1; cii!=casadi_s12+18; ++cii, ++ss) rr[*cii] = *ss;
  /* #325: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #326: @13 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w13);
  /* #327: @7 = zeros(3x1) */
  casadi_clear(w7, 3);
  /* #328: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #329: @30 = ones(3x1,1nz) */
  w30 = 1.;
  /* #330: @2 = mac(@8,@30,@2) */
  casadi_mtimes(w8, casadi_s1, (&w30), casadi_s13, w2, casadi_s4, w, 0);
  /* #331: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #332: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #333: @18 = 00 */
  /* #334: @30 = -1 */
  w30 = -1.;
  /* #335: @19 = 00 */
  /* #336: @39 = horzcat(@18, @30, @19) */
  rr=(&w39);
  *rr++ = w30;
  /* #337: @39 = @39' */
  /* #338: @30 = 1 */
  w30 = 1.;
  /* #339: @18 = 00 */
  /* #340: @19 = 00 */
  /* #341: @26 = horzcat(@30, @18, @19) */
  rr=(&w26);
  *rr++ = w30;
  /* #342: @26 = @26' */
  /* #343: @18 = zeros(3x1,0nz) */
  /* #344: @21 = horzcat(@39, @26, @18) */
  rr=w21;
  *rr++ = w39;
  *rr++ = w26;
  /* #345: @22 = @21' */
  casadi_trans(w21,casadi_s14, w22, casadi_s14, iw);
  /* #346: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<2; ++i) *rr++ = (- *cs++ );
  /* #347: @8 = mac(@22,@6,@8) */
  casadi_mtimes(w22, casadi_s14, w6, casadi_s1, w8, casadi_s1, w, 0);
  /* #348: @15 = mac(@8,@14,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #349: @2 = (@2+@15) */
  for (i=0, rr=w2, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #350: @7 = mac(@5,@2,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #351: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #352: @13 = @13' */
  /* #353: (@1[6:9] += @13) */
  for (rr=w1+6, ss=w13; rr!=w1+9; rr+=1) *rr += *ss++;
  /* #354: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #355: (@1[9:18] = @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #356: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #357: @39 = project(@3) */
  casadi_sparsify(w3, (&w39), casadi_s13, 0);
  /* #358: @26 = sparsity_cast(@4) */
  casadi_copy((&w4), 1, (&w26));
  /* #359: @30 = dot(@39, @26) */
  w30 = casadi_dot(1, (&w39), (&w26));
  /* #360: @30 = (@30/@11) */
  w30 /= w11;
  /* #361: @12 = (@12*@30) */
  w12 *= w30;
  /* #362: @12 = (@12/@11) */
  w12 /= w11;
  /* #363: @27 = (@27*@30) */
  w27 *= w30;
  /* #364: @12 = (@12-@27) */
  w12 -= w27;
  /* #365: @8 = (@24*@12) */
  for (i=0, rr=w8, cr=w24; i<9; ++i) (*rr++)  = ((*cr++)*w12);
  /* #366: @18 = 00 */
  /* #367: @12 = (-@4) */
  w12 = (- w4 );
  /* #368: @19 = 00 */
  /* #369: @27 = horzcat(@18, @12, @19) */
  rr=(&w27);
  *rr++ = w12;
  /* #370: @27 = @27' */
  /* #371: @18 = 00 */
  /* #372: @19 = 00 */
  /* #373: @12 = horzcat(@4, @18, @19) */
  rr=(&w12);
  *rr++ = w4;
  /* #374: @12 = @12' */
  /* #375: @18 = zeros(3x1,0nz) */
  /* #376: @22 = horzcat(@27, @12, @18) */
  rr=w22;
  *rr++ = w27;
  *rr++ = w12;
  /* #377: @21 = @22' */
  casadi_trans(w22,casadi_s14, w21, casadi_s14, iw);
  /* #378: @21 = (@25*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w25*(*cs++));
  /* #379: @6 = dense(@21) */
  casadi_densify(w21, casadi_s14, w6, 0);
  /* #380: @8 = (@8+@6) */
  for (i=0, rr=w8, cs=w6; i<9; ++i) (*rr++) += (*cs++);
  /* #381: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #382: @18 = 00 */
  /* #383: @27 = (-@4) */
  w27 = (- w4 );
  /* #384: @19 = 00 */
  /* #385: @12 = horzcat(@18, @27, @19) */
  rr=(&w12);
  *rr++ = w27;
  /* #386: @12 = @12' */
  /* #387: @18 = 00 */
  /* #388: @19 = 00 */
  /* #389: @27 = horzcat(@4, @18, @19) */
  rr=(&w27);
  *rr++ = w4;
  /* #390: @27 = @27' */
  /* #391: @18 = zeros(3x1,0nz) */
  /* #392: @21 = horzcat(@12, @27, @18) */
  rr=w21;
  *rr++ = w12;
  *rr++ = w27;
  /* #393: @22 = @21' */
  casadi_trans(w21,casadi_s14, w22, casadi_s14, iw);
  /* #394: @6 = mac(@33,@22,@6) */
  casadi_mtimes(w33, casadi_s1, w22, casadi_s14, w6, casadi_s1, w, 0);
  /* #395: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #396: @31 = (@31*@30) */
  w31 *= w30;
  /* #397: @31 = (@31/@9) */
  w31 /= w9;
  /* #398: @36 = (@36*@30) */
  w36 *= w30;
  /* #399: @32 = (@32*@36) */
  w32 *= w36;
  /* #400: @31 = (@31-@32) */
  w31 -= w32;
  /* #401: @34 = (@34*@31) */
  for (i=0, rr=w34; i<9; ++i) (*rr++) *= w31;
  /* #402: @18 = 00 */
  /* #403: @31 = (-@4) */
  w31 = (- w4 );
  /* #404: @19 = 00 */
  /* #405: @32 = horzcat(@18, @31, @19) */
  rr=(&w32);
  *rr++ = w31;
  /* #406: @32 = @32' */
  /* #407: @18 = 00 */
  /* #408: @19 = 00 */
  /* #409: @31 = horzcat(@4, @18, @19) */
  rr=(&w31);
  *rr++ = w4;
  /* #410: @31 = @31' */
  /* #411: @18 = zeros(3x1,0nz) */
  /* #412: @22 = horzcat(@32, @31, @18) */
  rr=w22;
  *rr++ = w32;
  *rr++ = w31;
  /* #413: @21 = @22' */
  casadi_trans(w22,casadi_s14, w21, casadi_s14, iw);
  /* #414: @21 = (@28*@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) (*rr++)  = (w28*(*cs++));
  /* #415: @23 = dense(@21) */
  casadi_densify(w21, casadi_s14, w23, 0);
  /* #416: @34 = (@34+@23) */
  for (i=0, rr=w34, cs=w23; i<9; ++i) (*rr++) += (*cs++);
  /* #417: @17 = mac(@34,@40,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w40+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #418: @6 = (@6+@17) */
  for (i=0, rr=w6, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #419: @8 = (@8+@6) */
  for (i=0, rr=w8, cs=w6; i<9; ++i) (*rr++) += (*cs++);
  /* #420: @5 = mac(@16,@8,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #421: @5 = reshape(@5) */
  /* #422: (@1[9:18] += @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #423: @43 = @1[6:18] */
  for (rr=w43, ss=w1+6; ss!=w1+18; ss+=1) *rr++ = *ss;
  /* #424: (@0[20, 23, 26, 29, 35, 41, 47, 53, 59, 65, 71, 77] = @43) */
  for (cii=casadi_s15, rr=w0, ss=w43; cii!=casadi_s15+12; ++cii, ++ss) rr[*cii] = *ss;
  /* #425: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #426: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #427: @44 = input[1][0] */
  casadi_copy(arg[1], 4, w44);
  /* #428: @28 = @44[0] */
  for (rr=(&w28), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #429: @32 = input[3][0] */
  w32 = arg[3] ? arg[3][0] : 0;
  /* #430: @28 = (@28/@32) */
  w28 /= w32;
  /* #431: @13 = @28[0, 0, 0] */
  for (cii=casadi_s9, rr=w13, ss=(&w28); cii!=casadi_s9+3; ++cii) *rr++ = ss[*cii];
  /* #432: @7 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w7);
  /* #433: @3 = mac(@13,@7,@3) */
  casadi_mtimes(w13, casadi_s16, w7, casadi_s4, w3, casadi_s4, w, 0);
  /* #434: @3 = (@4*@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #435: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  /* #436: @3 = @3' */
  /* #437: (@1[3:6] += @3) */
  for (rr=w1+3, ss=w3; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #438: @3 = zeros(1x3) */
  casadi_clear(w3, 3);
  /* #439: (@1[6:9] = @3) */
  for (rr=w1+6, ss=w3; rr!=w1+9; rr+=1) *rr = *ss++;
  /* #440: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #441: (@1[9:18] = @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #442: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #443: @3 = ones(3x3,3nz) */
  casadi_fill(w3, 3, 1.);
  /* #444: @16 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w16);
  /* #445: @24 = (@25*@24) */
  for (i=0, rr=w24, cs=w24; i<9; ++i) (*rr++)  = (w25*(*cs++));
  /* #446: @16 = (@16+@24) */
  for (i=0, rr=w16, cs=w24; i<9; ++i) (*rr++) += (*cs++);
  /* #447: @24 = zeros(3x3) */
  casadi_clear(w24, 9);
  /* #448: @24 = mac(@33,@40,@24) */
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w40+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #449: @16 = (@16+@24) */
  for (i=0, rr=w16, cs=w24; i<9; ++i) (*rr++) += (*cs++);
  /* #450: @5 = mac(@3,@16,@5) */
  casadi_mtimes(w3, casadi_s16, w16, casadi_s1, w5, casadi_s1, w, 0);
  /* #451: @5 = reshape(@5) */
  /* #452: (@1[9:18] += @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #453: @43 = @1[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17] */
  for (cii=casadi_s17, rr=w43, ss=w1; cii!=casadi_s17+12; ++cii) *rr++ = ss[*cii];
  /* #454: (@0[7, 11, 15, 30, 36, 42, 48, 54, 60, 66, 72, 78] = @43) */
  for (cii=casadi_s18, rr=w0, ss=w43; cii!=casadi_s18+12; ++cii, ++ss) rr[*cii] = *ss;
  /* #455: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #456: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #457: @13 = @28[0, 0, 0] */
  for (cii=casadi_s9, rr=w13, ss=(&w28); cii!=casadi_s9+3; ++cii) *rr++ = ss[*cii];
  /* #458: @3 = mac(@13,@7,@3) */
  casadi_mtimes(w13, casadi_s19, w7, casadi_s4, w3, casadi_s4, w, 0);
  /* #459: @3 = (@4*@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #460: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  /* #461: @3 = @3' */
  /* #462: (@1[3:6] += @3) */
  for (rr=w1+3, ss=w3; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #463: @3 = zeros(1x3) */
  casadi_clear(w3, 3);
  /* #464: (@1[6:9] = @3) */
  for (rr=w1+6, ss=w3; rr!=w1+9; rr+=1) *rr = *ss++;
  /* #465: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #466: (@1[9:18] = @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #467: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #468: @3 = ones(3x3,3nz) */
  casadi_fill(w3, 3, 1.);
  /* #469: @5 = mac(@3,@16,@5) */
  casadi_mtimes(w3, casadi_s19, w16, casadi_s1, w5, casadi_s1, w, 0);
  /* #470: @5 = reshape(@5) */
  /* #471: (@1[9:18] += @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #472: @43 = @1[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17] */
  for (cii=casadi_s17, rr=w43, ss=w1; cii!=casadi_s17+12; ++cii) *rr++ = ss[*cii];
  /* #473: (@0[8, 12, 16, 31, 37, 43, 49, 55, 61, 67, 73, 79] = @43) */
  for (cii=casadi_s20, rr=w0, ss=w43; cii!=casadi_s20+12; ++cii, ++ss) rr[*cii] = *ss;
  /* #474: @1 = zeros(18x1) */
  casadi_clear(w1, 18);
  /* #475: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #476: @13 = @28[0, 0, 0] */
  for (cii=casadi_s9, rr=w13, ss=(&w28); cii!=casadi_s9+3; ++cii) *rr++ = ss[*cii];
  /* #477: @3 = mac(@13,@7,@3) */
  casadi_mtimes(w13, casadi_s21, w7, casadi_s4, w3, casadi_s4, w, 0);
  /* #478: @3 = (@4*@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #479: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  /* #480: @3 = @3' */
  /* #481: (@1[3:6] += @3) */
  for (rr=w1+3, ss=w3; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #482: @3 = zeros(1x3) */
  casadi_clear(w3, 3);
  /* #483: (@1[6:9] = @3) */
  for (rr=w1+6, ss=w3; rr!=w1+9; rr+=1) *rr = *ss++;
  /* #484: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #485: (@1[9:18] = @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr = *ss++;
  /* #486: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #487: @3 = ones(3x3,3nz) */
  casadi_fill(w3, 3, 1.);
  /* #488: @5 = mac(@3,@16,@5) */
  casadi_mtimes(w3, casadi_s21, w16, casadi_s1, w5, casadi_s1, w, 0);
  /* #489: @5 = reshape(@5) */
  /* #490: (@1[9:18] += @5) */
  for (rr=w1+9, ss=w5; rr!=w1+18; rr+=1) *rr += *ss++;
  /* #491: @43 = @1[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17] */
  for (cii=casadi_s17, rr=w43, ss=w1; cii!=casadi_s17+12; ++cii) *rr++ = ss[*cii];
  /* #492: (@0[9, 13, 17, 32, 38, 44, 50, 56, 62, 68, 74, 80] = @43) */
  for (cii=casadi_s22, rr=w0, ss=w43; cii!=casadi_s22+12; ++cii, ++ss) rr[*cii] = *ss;
  /* #493: @45 = @0' */
  casadi_trans(w0,casadi_s24, w45, casadi_s23, iw);
  /* #494: output[0][0] = @45 */
  casadi_copy(w45, 81, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_f_X_fcn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int grad_f_X_fcn_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_f_X_fcn_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_f_X_fcn_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int grad_f_X_fcn_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_f_X_fcn_release(int mem) {
}

CASADI_SYMBOL_EXPORT void grad_f_X_fcn_incref(void) {
}

CASADI_SYMBOL_EXPORT void grad_f_X_fcn_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int grad_f_X_fcn_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int grad_f_X_fcn_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real grad_f_X_fcn_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_f_X_fcn_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_f_X_fcn_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_f_X_fcn_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s25;
    case 1: return casadi_s26;
    case 2: return casadi_s27;
    case 3: return casadi_s27;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_f_X_fcn_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int grad_f_X_fcn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 19;
  if (sz_w) *sz_w = 394;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_grad_f_X_fcn(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[508];
  casadi_int iw[19];
  const casadi_real* arg[8] = {0};
  casadi_real* res[2] = {0};
  if (argc>5) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_f_X_fcn\" failed. Too many input arguments (%d, max 5)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_f_X_fcn\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s25, w+114);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+18, casadi_s26, w+114);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+22, casadi_s27, w+114);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+23, casadi_s27, w+114);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+24, casadi_s1, w+114);
  --resc;
  res[0] = w+33;
  grad_f_X_fcn_incref();
  mem = grad_f_X_fcn_checkout();
  i = grad_f_X_fcn(arg, res, iw, w+114, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_f_X_fcn\" failed.");
  grad_f_X_fcn_release(mem);
  grad_f_X_fcn_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s23, res[0]);
}
#endif

casadi_int main_grad_f_X_fcn(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int iw[19];
  casadi_real w[508];
  const casadi_real* arg[8];
  casadi_real* res[2];
  arg[0] = w+0;
  arg[1] = w+18;
  arg[2] = w+22;
  arg[3] = w+23;
  arg[4] = w+24;
  res[0] = w+33;
  a = w;
  for (j=0; j<33; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = grad_f_X_fcn(arg, res, iw, w+114, 0);
  if (flag) return flag;
  r = w+33;
  for (j=0; j<81; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[13];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_grad_f_X_fcn(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "grad_f_X_fcn")==0) {
    mex_grad_f_X_fcn(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'grad_f_X_fcn'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "grad_f_X_fcn")==0) {
    return main_grad_f_X_fcn(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'grad_f_X_fcn'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
